import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { fetchCampaignData } from "./utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children, campaignData  }) {

  return (
    <html lang="en">
      <head>
      <link
          rel="icon"
     
          href={campaignData?.image || "/xplore-logo.svg"}
        />
        <meta name="apple-itunes-app" content="app-clip-bundle-id=com.xircular.XplorePromote.Clip, app-clip-display=card" />
        <link rel="canonical" href="https://appclip.apple.com/id?p=com.xircular.XplorePromote.Clip" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}